build-job:
  stage: build
  tags:
    - sample
  cache:
    paths:
      - node_modules/
  script:
    - echo "Building the application..."
    - npm install
    - echo "Build successful!"

test-job:
  stage: test
  tags:
    - sample
  script:
    - echo "Running tests..."
    - npm test
  artifacts:
    paths:
      - test-results/

deploy-job:
  stage: deploy
  tags:
    - sample
  script:
    - echo "Deploying the application..."
    - echo "Application deployed successfully!"