stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - sample
  script:
    - echo "Building the application..."
    - node -v  # Verify Node.js version
    - npm -v   # Verify npm version
    - npm install
    - echo "Build successful!"

test-job:
  stage: test
  tags:
    - sample
  script:
    - echo "Running tests..."
    - node -v  # Verify Node.js version
    - npm -v   # Verify npm version
    - npm install  # Reinstall dependencies
    - npm test

deploy-job:
  stage: deploy
  tags:
    - sample
  script:
    - echo "Deploying the application..."
    - echo "Application deployed successfully!"